<?php
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

$entrevistas = [
 ['area'=>'Salud','nombre'=>'Dra. Valentina Ríos','profesion'=>'Médica general','imagen'=>'img/salud.jpg','audio'=>'audio/salud.mp3','orientacion'=>'Conoce qué problemas disfrutas resolver y busca experiencias reales antes de elegir. Una conversación o un voluntariado puede aclararte mucho más que una lista de carreras.','carrera'=>'La medicina exige constancia y empatía. Aprende a pedir ayuda, cuida tu descanso y recuerda que detrás de cada caso hay una persona.'],
 ['area'=>'Salud','nombre'=>'Dra. Valentina Ríos','profesion'=>'Médica general','imagen'=>'img/salud.jpg','audio'=>'audio/salud.mp3','orientacion'=>'Conoce qué problemas disfrutas resolver y busca experiencias reales antes de elegir. Una conversación o un voluntariado puede aclararte mucho más que una lista de carreras.','carrera'=>'La medicina exige constancia y empatía. Aprende a pedir ayuda, cuida tu descanso y recuerda que detrás de cada caso hay una persona.'],
 ['area'=>'Humanidades','nombre'=>'Santiago Mejía','profesion'=>'Abogado y mediador','imagen'=>'img/humanidades.jpg','audio'=>'audio/humanidades.mp3','orientacion'=>'Pregúntate qué conversaciones despiertan tu curiosidad. Si disfrutas comprender a las personas, argumentar y transformar conflictos, explora las humanidades.','carrera'=>'Lee más allá de las materias obligatorias y practica explicar ideas complejas con claridad. La escucha es tan importante como una buena argumentación.'],
 ['area'=>'Ciencias','nombre'=>'Laura Fernández','profesion'=>'Bióloga investigadora','imagen'=>'img/ciencias.jpg','audio'=>'audio/ciencias.mp3','orientacion'=>'No busques una carrera perfecta: identifica las preguntas que te emocionaría investigar durante años y prueba talleres o semilleros relacionados.','carrera'=>'Acepta que equivocarse es parte del método. Documenta tus procesos, fortalece las matemáticas y conserva siempre la curiosidad.'],
 ['area'=>'Tecnología','nombre'=>'Daniel Torres','profesion'=>'Ingeniero de software','imagen'=>'img/tecnologia.jpg','audio'=>'audio/tecnologia.mp3','orientacion'=>'Construye un proyecto pequeño antes de decidir. La tecnología tiene muchos caminos y experimentar te mostrará si disfrutas crear soluciones digitales.','carrera'=>'Practica con proyectos propios, aprende a trabajar en equipo y no memorices herramientas: comprende los fundamentos y mantente aprendiendo.'],
 ['area'=>'Arte y Diseño','nombre'=>'Camila Ortiz','profesion'=>'Diseñadora visual','imagen'=>'img/arte-diseno.jpg','audio'=>'audio/arte-diseno.mp3','orientacion'=>'Observa qué haces incluso cuando nadie te lo pide. Si dibujar, imaginar o comunicar visualmente te absorbe, convierte esa curiosidad en un portafolio.','carrera'=>'Guarda cada proceso, no solo el resultado. Aprende a recibir críticas sin perder tu voz y diseña pensando en las personas que usarán tu trabajo.'],
 ['area'=>'Entretenimiento','nombre'=>'Mateo Salazar','profesion'=>'Productor audiovisual','imagen'=>'img/entretenimiento.jpg','audio'=>'audio/entretenimiento.mp3','orientacion'=>'Explora teatro, música, cine o producción con proyectos cortos. El entretenimiento reúne perfiles creativos, técnicos y de gestión.','carrera'=>'Sé puntual, crea una red de colaboradores y termina lo que empiezas. Un proyecto completo enseña más que muchas ideas guardadas.']
];

echo json_encode(['ok'=>true,'total'=>count($entrevistas),'entrevistas'=>$entrevistas], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);